[package]
name = "dedupe"
version = "1.0.0"
authors = ["Justin Lambert <mastfish@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
walkdir = "2"
blake2 = "0.8.1"
digest = { version = "0.8.1", features = ["std"]}
rayon = "1.3"
chashmap = "2.2"
structopt = "0.3"

[dependencies.gtk]
version = "0.8.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]

[lib]
name = "dupelib"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

