[package]
name = "dedupe"
version = "1.0.0"
authors = ["Justin Lambert <mastfish@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
walkdir = "2"
blake2 = "0.8.1"
digest = { version = "0.9.0", features = ["std"]}
rayon = "1.3"
chashmap = "2.2"
structopt = "0.3"
druid = { git = "https://github.com/xi-editor/druid.git", rev = "47be1da", version = "0.5" }
[lib]
name = "dupelib"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

