[package]
name = "dedupe"
version = "1.0.0"
authors = ["Justin Lambert <mastfish@gmail.com>"]
publish = false
edition = "2018"
default-run = "cli"

[profile.release]
lto = "thin"

[dependencies]
walkdir = "2"
blake2 = "0.9.0"
digest = { version = "0.9.0", features = ["std"]}
rayon = "1.4"
chashmap = "2.2"
structopt = "0.3"
druid = "0.6"
crossbeam-channel = "0.4"
[lib]
name = "dupelib"
path = "src/lib.rs"
