[package]
name = "dedupe"
version = "1.0.0"
authors = ["Justin Lambert <mastfish@gmail.com>"]
publish = false

[dependencies]
walkdir = "2"
blake2 = "0.7"
digest = { version = "0.7", features = ["std"]}
rayon = "1.0"
chashmap = "2.2"
structopt = "0.2"
