[package]
name = "dedupe"
version = "2.2.1"
authors = ["Justin Lambert <mastfish@gmail.com>"]
publish = false
edition = "2018"
default-run = "cli"

[profile.release]
lto = "thin"

[dependencies]
walkdir = "2"
rayon = "1.4"
structopt = "0.3"
druid = "0.6"
crossbeam-channel = "0.4"
typed-arena = "2"
seahash = "4.0.1"
dashmap = "3.11.10"

[lib]
name = "dupelib"
path = "src/lib.rs"


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false