[package]
name = "dedupe"
version = "2.2.1"
authors = ["Justin Lambert <mastfish@gmail.com>"]
publish = false
edition = "2021"
default-run = "cli"

[profile.release]
lto = "thin"

[dependencies]
walkdir = "2"
rayon = "1"
structopt = "0"
crossbeam-channel = "0"
typed-arena = "2"
seahash = "4"
dashmap = "5"
druid =  {version = "0",optional = true}

[lib]
name = "dupelib"
path = "src/lib.rs"


[dev-dependencies]
criterion = "0"


[[bench]]
name = "my_benchmark"
harness = false

[features]
gui = ["druid"]
