[package]
name = "dedupe"
version = "2.2.1"
authors = ["Justin Lambert <mastfish@gmail.com>"]
publish = false
edition = "2021"
default-run = "cli"

[profile.release]
lto = "thin"

[dependencies]
walkdir = "2"
rayon = "1.5"
structopt = "0.3"
druid = "0.7"
crossbeam-channel = "0.5"
typed-arena = "2"
seahash = "4.1.0"
dashmap = "4.0.2"

[lib]
name = "dupelib"
path = "src/lib.rs"


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
