on: release
name: Handle Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --release
      - uses: Shopify/upload-to-release@master
        with:
          name: my-artifact
          path: target/release/main
          repo-token: ${{ secrets.GITHUB_TOKEN }}
