on: release
name: Build release binaries
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - uses: Shopify/upload-to-release@master
      if: matrix.os != 'windows-latest'
      with:
        name: ${{ matrix.os }}
        label: ${{ matrix.os }}
        path: target/release/main
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: Shopify/upload-to-release@master
      if: matrix.os == 'windows-latest'
      with:
        name: ${{ matrix.os }}.exe
        label: ${{ matrix.os }}
        path: target\release\main.exe
        repo-token: ${{ secrets.GITHUB_TOKEN }}
