name: Test Rust project
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: linux deps
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get install libgtk-3-dev
    - name: macos deps
      if: matrix.os == 'macOS-latest'
      run: |
          brew install gtk+3
    - name: Run tests
      run: cargo test --all
